local mod = get_mod("ManyMoreTry")

mod:add_global_localize_strings({
	loc_mod_mmt_save = {
		en = "Save Mission",
		["zh-cn"] = "保存任务",
		ru = "Сохранить миссию",
		["zh-tw"] = "儲存任務",
	},
})

return {
	mod_name = {
		en = "Many More Try",
		["zh-cn"] = "再来很多局",
		ru = "Ещё больше попыток",
		["zh-tw"] = "繼續再來更多局",
	},
	mod_description = {
		en = "Mission ID saving/sharing mod. Check commands with '/mmt' prefix for details.",
		["zh-cn"] = "任务 ID 保存/分享模组。用法详见带有“/mmt”前缀的命令。",
		ru = "Many More Try - Мод позволяет сохранять и передавать идентификатор миссии. Для получения подробной информации проверьте команды с префиксом «/mmt».",
		["zh-tw"] = "任務 ID 儲存/分享模組，使用「/mmt」開頭的指令以查看詳情。",
	},
	text_expired = {
		en = "Expired",
		["zh-cn"] = "已过期",
		ru = "Срок действия истёк",
		["zh-tw"] = "已過期",
	},
	text_started = {
		en = "Started #hrs ago",
		["zh-cn"] = "开始于 # 小时前",
		ru = "С начала миссии прошло часов: #",
		["zh-tw"] = "# 小時前開始",
	},
	msg_already_saved = {
		en = "Already saved: ",
		["zh-cn"] = "已保存过：",
		ru = "Уже сохранена!",
		["zh-tw"] = "已經儲存過：",
	},
	msg_saved = {
		en = "Saved mission: ",
		["zh-cn"] = "保存了任务：",
		ru = "Сохранена миссия: ",
		["zh-tw"] = "已儲存任務：",
	},
	msg_command_busy = {
		en = "Error: command is busy",
		["zh-cn"] = "错误：命令正忙",
		ru = "Ошибка: команда в работе",
		["zh-tw"] = "錯誤：指令正在執行中",
	},
	msg_not_in_party = {
		en = "Error: private game is enabled in the Mission Board, but you are not in a Strike Team",
		["zh-cn"] = "错误：任务面板中已启用私人游戏，但你不在打击小队中",
		ru = "Ошибка: закрытая игра включена в меню миссий, но вы не состоите в Ударной группе",
		["zh-tw"] = "錯誤：任務面板啟用了私人遊戲，但你不在打擊小隊中",
	},
	msg_on_your_way_to = {
		en = "On your way to: ",
		["zh-cn"] = "正在前往：",
		ru = "Вы направляетесь в: ",
		["zh-tw"] = "正在前往：",
	},
	msg_no_saved_mission = {
		en = "No saved mission",
		["zh-cn"] = "未保存任务",
		ru = "Нет сохранённых миссий",
		["zh-tw"] = "沒有儲存的任務",
	},
	msg_saved_mission = {
		en = "Saved missions:",
		["zh-cn"] = "保存的任务：",
		ru = "Сохранённые миссии:",
		["zh-tw"] = "已儲存的任務：",
	},
	msg_no_valid_last_mission = {
		en = "Error: no valid last mission",
		["zh-cn"] = "错误：未找到有效的上次任务",
		ru = "Ошибка: нет действительной последней миссии",
		["zh-tw"] = "錯誤：找不到有效的上一個任務",
	},
	msg_invalid_number = {
		en = "Error: invalid number",
		["zh-cn"] = "错误：编号无效",
		ru = "Ошибка: неверный номер",
		["zh-tw"] = "錯誤：編號無效",
	},
	msg_expired = {
		en = "Error: mission is expired",
		["zh-cn"] = "错误：任务已过期",
		ru = "Ошибка: срок действия миссии истёк",
		["zh-tw"] = "錯誤：任務已過期",
	},
	msg_expired_safe_to_delete = {
		en = "Error: mission is expired, please remove manually",
		["zh-cn"] = "错误：任务已过期，请手动删除",
		ru = "Ошибка: срок действия миссии истёк, удалите её вручную",
		["zh-tw"] = "錯誤：任務已過期，請手動移除",
	},
	msg_level_required = {
		en = "Error: character hasn't reached the required level of this mission",
		["zh-cn"] = "错误：角色未达到任务所需等级",
		ru = "Ошибка: персонаж не достиг необходимого уровня для этой миссии",
		["zh-tw"] = "錯誤：角色尚未達到此任務所需的等級",
	},
	msg_team_not_available = {
		en = "Error: team is not available for matchmaking",
		["zh-cn"] = "错误：队伍还无法进行匹配",
		ru = "Ошибка: команда недоступна для подбора миссии",
		["zh-tw"] = "錯誤：隊伍目前無法進行配對",
	},
	msg_unknown_err = {
		en = "Error: unknown reason",
		["zh-cn"] = "错误：未知原因",
		ru = "Ошибка: неизвестная причина",
		["zh-tw"] = "錯誤：未知原因",
	},
	msg_removed = {
		en = "Removed mission: ",
		["zh-cn"] = "删除了任务：",
		ru = "Удалена миссия: ",
		["zh-tw"] = "已刪除任務：",
	},
	msg_cleared = {
		en = "Cleared # mission(s)",
		["zh-cn"] = "清理了 # 个任务",
		ru = "Очищено миссий: #",
		["zh-tw"] = "已清理 # 個任務",
	},
	msg_help_queue = {
		en = "Type {#color(0,192,255)}/mmt mission_number_or_id{#reset()} to queue (e.g. {#color(0,192,255)}/mmt 1{#reset()})",
		["zh-cn"] = "输入 {#color(0,192,255)}/mmt 任务编号或ID{#reset()} 开始匹配（例：{#color(0,192,255)}/mmt 1{#reset()}）",
		ru = "Напишите {#color(0,192,255)}/mmt номер_миссии_или_идентификатор{#reset()}, чтобы запустить её (например {#color(0,192,255)}/mmt 1{#reset()})",
		["zh-tw"] = "輸入 {#color(0,192,255)}/mmt 任務編號或ID{#reset()} 以開始配對（例如：{#color(0,192,255)}/mmt 1{#reset()}）",
	},
	msg_help_del = {
		en = "Type {#color(0,192,255)}/mmtdel mission_number{#reset()} to remove",
		["zh-cn"] = "输入 {#color(0,192,255)}/mmtdel 任务编号{#reset()} 删除",
		ru = "Напишите {#color(0,192,255)}/mmtdel номер_миссии{#reset()}, чтобы удалить её",
		["zh-tw"] = "輸入 {#color(0,192,255)}/mmtdel 任務編號{#reset()} 以刪除",
	},
	msg_help_clear = {
		en = "Type {#color(0,192,255)}/mmtclear hours_ago{#reset()} to clear missions started longer than 'hours_ago' hrs ago",
		["zh-cn"] = "输入 {#color(0,192,255)}/mmtclear 小时数{#reset()} 清理开始时间超过相应小时的任务",
		ru = "Напишите {#color(0,192,255)}/mmtclear часов_назад{#reset()}, чтобы очистить миссии старше «часов_назад»",
		["zh-tw"] = "輸入 {#color(0,192,255)}/mmtclear 小時數{#reset()} 以清除開始時間超過此小時數的任務",
	},
	msg_nothing_to_export = {
		en = "Error: no mission to export",
		["zh-cn"] = "错误：没有能导出的任务",
		ru = "Ошибка: нет миссий для экспорта",
		["zh-tw"] = "錯誤：沒有可匯出的任務",
	},
	msg_copy_err = {
		en = "Error: failed to copy to clipboard",
		["zh-cn"] = "错误：复制到剪贴板失败",
		ru = "Ошибка: не удалось скопировать в буфер обмена",
		["zh-tw"] = "錯誤：無法複製至剪貼簿",
	},
	msg_data_copied = {
		en = "Data copied to clipboard",
		["zh-cn"] = "数据已复制到剪贴板",
		ru = "Данные скопированы в буфер обмена",
		["zh-tw"] = "資料已複製至剪貼簿",
	},
	msg_help_export = {
		en = "Type {#color(0,192,255)}/mmtexport{#reset()} to export all missions",
		["zh-cn"] = "输入 {#color(0,192,255)}/mmtexport{#reset()} 导出所有任务",
		ru = "Напишите {#color(0,192,255)}/mmtexport{#reset()}, чтобы экспортировать все миссии",
		["zh-tw"] = "輸入 {#color(0,192,255)}/mmtexport{#reset()} 以匯出所有任務",
	},
	msg_help_import = {
		en = "Type {#color(0,192,255)}/mmtimport mission_id{#reset()} to import",
		["zh-cn"] = "输入 {#color(0,192,255)}/mmtimport 任务ID{#reset()} 导入任务",
		ru = "Напишите {#color(0,192,255)}/mmtimport идентификатор_миссии{#reset()}, чтобы импортировать миссию",
		["zh-tw"] = "輸入 {#color(0,192,255)}/mmtimport 任務ID{#reset()} 以匯入任務",
	},
	msg_import_invalid_mission = {
		en = "Error: invalid mission ID",
		["zh-cn"] = "错误：任务 ID 无效",
		ru = "Ошибка: неправильный идентификатор миссии",
		["zh-tw"] = "錯誤：任務 ID 無效",
	},
	cmd_main = {
		en = "View and queue saved missions",
		["zh-cn"] = "查看和匹配已保存的任务",
		ru = "Просмотр и постановка в очередь сохранённых миссий",
		["zh-tw"] = "查看並進行已儲存的任務配對",
	},
	cmd_lm = {
		en = "Replay the last mission",
		["zh-cn"] = "重玩上次进行的任务",
		ru = "Переиграть последнюю миссию",
		["zh-tw"] = "重新體驗上一個任務",
	},
	cmd_del = {
		en = "Remove saved mission",
		["zh-cn"] = "删除已保存的任务",
		ru = "Удалить сохранённую миссию",
		["zh-tw"] = "刪除已儲存的任務",
	},
	cmd_export = {
		en = "Export all saved missions",
		["zh-cn"] = "导出所有已保存的任务",
		ru = "Экспортировать все сохранённые миссии",
		["zh-tw"] = "匯出所有已儲存的任務",
	},
	cmd_import = {
		en = "Import a mission ID",
		["zh-cn"] = "导入一个任务 ID",
		ru = "Импортировать идентификатор миссии",
		["zh-tw"] = "匯入一個任務 ID",
	},
	cmd_clear = {
		en = "Clear missions started X hours ago",
		["zh-cn"] = "清理已开始了 X 小时的任务",
		ru = "Убрать миссии, начатые X часов назад",
		["zh-tw"] = "清除在 X 小時前開始的任務",
	},
	cmd_get = {
		en = "Open mission history online website",
		["zh-cn"] = "打开任务历史记录在线网站",
		ru = "Открыть онлайн-сайт с историей миссий",
		["zh-tw"] = "打開任務歷史紀錄的線上網站",
	},
}
