-- Generated by dev/generate_dialogue_data.py. Do not edit manually.

return {
	adamant_female_a = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 6,
			sound_events = {
				"loc_adamant_female_a__com_wheel_vo_for_the_emperor_01",
				"loc_adamant_female_a__com_wheel_vo_for_the_emperor_02",
				"loc_adamant_female_a__com_wheel_vo_for_the_emperor_03",
				"loc_adamant_female_a__com_wheel_vo_for_the_emperor_04",
				"loc_adamant_female_a__com_wheel_vo_for_the_emperor_05",
				"loc_adamant_female_a__com_wheel_vo_for_the_emperor_06",
			},
			sound_events_duration = {
				1.76,
				1.486677,
				1.25201,
				1.534667,
				1.444667,
				1.581333,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
				"For the Lex!",
				"For the Lex!",
				"For Atoma!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_adamant_female_a__com_wheel_vo_for_the_emperor_01",
				"loc_adamant_female_a__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				1.76,
				1.486677,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
			},
			randomize_indexes = {},
		},
	},
	adamant_female_b = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 3,
			sound_events = {
				"loc_adamant_female_b__com_wheel_vo_for_the_emperor_01",
				"loc_adamant_female_b__com_wheel_vo_for_the_emperor_03",
				"loc_adamant_female_b__com_wheel_vo_for_the_emperor_05",
			},
			sound_events_duration = {
				1.616354,
				1.393708,
				1.415219,
			},
			texts = {
				"For the Emperor!",
				"For the Lex!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 1,
			sound_events = {
				"loc_adamant_female_b__com_wheel_vo_for_the_emperor_01",
			},
			sound_events_duration = {
				1.616354,
			},
			texts = {
				"For the Emperor!",
			},
			randomize_indexes = {},
		},
	},
	adamant_female_c = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 3,
			sound_events = {
				"loc_adamant_female_c__com_wheel_vo_for_the_emperor_01",
				"loc_adamant_female_c__com_wheel_vo_for_the_emperor_03",
				"loc_adamant_female_c__com_wheel_vo_for_the_emperor_05",
			},
			sound_events_duration = {
				1.096823,
				1.131677,
				1.180115,
			},
			texts = {
				"For the Emperor!",
				"For the Lex!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 1,
			sound_events = {
				"loc_adamant_female_c__com_wheel_vo_for_the_emperor_01",
			},
			sound_events_duration = {
				1.096823,
			},
			texts = {
				"For the Emperor!",
			},
			randomize_indexes = {},
		},
	},
	adamant_male_a = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 3,
			sound_events = {
				"loc_adamant_male_a__com_wheel_vo_for_the_emperor_01",
				"loc_adamant_male_a__com_wheel_vo_for_the_emperor_03",
				"loc_adamant_male_a__com_wheel_vo_for_the_emperor_05",
			},
			sound_events_duration = {
				1.309875,
				1.119365,
				1.616792,
			},
			texts = {
				"For the Emperor!",
				"For the Lex!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 1,
			sound_events = {
				"loc_adamant_male_a__com_wheel_vo_for_the_emperor_01",
			},
			sound_events_duration = {
				1.309875,
			},
			texts = {
				"For the Emperor!",
			},
			randomize_indexes = {},
		},
	},
	adamant_male_b = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 4,
			sound_events = {
				"loc_adamant_male_b__com_wheel_vo_for_the_emperor_01",
				"loc_adamant_male_b__com_wheel_vo_for_the_emperor_02",
				"loc_adamant_male_b__com_wheel_vo_for_the_emperor_05",
				"loc_adamant_male_b__com_wheel_vo_for_the_emperor_06",
			},
			sound_events_duration = {
				1.256667,
				1.746,
				1.329333,
				1.61,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
				"For Atoma!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_adamant_male_b__com_wheel_vo_for_the_emperor_01",
				"loc_adamant_male_b__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				1.256667,
				1.746,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
			},
			randomize_indexes = {},
		},
	},
	adamant_male_c = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 6,
			sound_events = {
				"loc_adamant_male_c__com_wheel_vo_for_the_emperor_01",
				"loc_adamant_male_c__com_wheel_vo_for_the_emperor_02",
				"loc_adamant_male_c__com_wheel_vo_for_the_emperor_03",
				"loc_adamant_male_c__com_wheel_vo_for_the_emperor_04",
				"loc_adamant_male_c__com_wheel_vo_for_the_emperor_05",
				"loc_adamant_male_c__com_wheel_vo_for_the_emperor_06",
			},
			sound_events_duration = {
				1.737594,
				1.736906,
				1.203479,
				1.55976,
				1.425667,
				1.780896,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
				"For the Lex!",
				"For the Lex!",
				"For Atoma!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_adamant_male_c__com_wheel_vo_for_the_emperor_01",
				"loc_adamant_male_c__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				1.737594,
				1.736906,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
			},
			randomize_indexes = {},
		},
	},
	broker_female_a = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 3,
			sound_events = {
				"loc_broker_female_a__com_wheel_vo_for_the_emperor_01",
				"loc_broker_female_a__com_wheel_vo_for_the_emperor_02",
				"loc_broker_female_a__com_wheel_vo_for_the_emperor_03",
			},
			sound_events_duration = {
				1.650646,
				1.642667,
				1.949333,
			},
			texts = {
				"For the Conclave!",
				"For Atoma!",
				"For freedom!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 1,
			sound_events = {
				"loc_broker_female_a__com_wheel_vo_for_the_emperor_01",
			},
			sound_events_duration = {
				1.650646,
			},
			texts = {
				"For the Conclave!",
			},
			randomize_indexes = {},
		},
	},
	broker_female_b = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 3,
			sound_events = {
				"loc_broker_female_b__com_wheel_vo_for_the_emperor_01",
				"loc_broker_female_b__com_wheel_vo_for_the_emperor_02",
				"loc_broker_female_b__com_wheel_vo_for_the_emperor_03",
			},
			sound_events_duration = {
				1.49901,
				1.139,
				1.217,
			},
			texts = {
				"For the Conclave!",
				"For Atoma!",
				"For freedom!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 1,
			sound_events = {
				"loc_broker_female_b__com_wheel_vo_for_the_emperor_01",
			},
			sound_events_duration = {
				1.49901,
			},
			texts = {
				"For the Conclave!",
			},
			randomize_indexes = {},
		},
	},
	broker_female_c = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 3,
			sound_events = {
				"loc_broker_female_c__com_wheel_vo_for_the_emperor_01",
				"loc_broker_female_c__com_wheel_vo_for_the_emperor_02",
				"loc_broker_female_c__com_wheel_vo_for_the_emperor_03",
			},
			sound_events_duration = {
				2.150563,
				1.930958,
				2.751375,
			},
			texts = {
				"For the Conclave!",
				"For Atoma!",
				"For freedom!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 1,
			sound_events = {
				"loc_broker_female_c__com_wheel_vo_for_the_emperor_01",
			},
			sound_events_duration = {
				2.150563,
			},
			texts = {
				"For the Conclave!",
			},
			randomize_indexes = {},
		},
	},
	broker_male_a = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 3,
			sound_events = {
				"loc_broker_male_a__com_wheel_vo_for_the_emperor_01",
				"loc_broker_male_a__com_wheel_vo_for_the_emperor_02",
				"loc_broker_male_a__com_wheel_vo_for_the_emperor_03",
			},
			sound_events_duration = {
				1.758208,
				1.517542,
				1.506813,
			},
			texts = {
				"For the Conclave!",
				"For Atoma!",
				"For freedom!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 1,
			sound_events = {
				"loc_broker_male_a__com_wheel_vo_for_the_emperor_01",
			},
			sound_events_duration = {
				1.758208,
			},
			texts = {
				"For the Conclave!",
			},
			randomize_indexes = {},
		},
	},
	broker_male_b = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 3,
			sound_events = {
				"loc_broker_male_b__com_wheel_vo_for_the_emperor_01",
				"loc_broker_male_b__com_wheel_vo_for_the_emperor_02",
				"loc_broker_male_b__com_wheel_vo_for_the_emperor_03",
			},
			sound_events_duration = {
				2.112688,
				1.655885,
				1.622573,
			},
			texts = {
				"For the Conclave!",
				"For Atoma!",
				"For freedom!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 1,
			sound_events = {
				"loc_broker_male_b__com_wheel_vo_for_the_emperor_01",
			},
			sound_events_duration = {
				2.112688,
			},
			texts = {
				"For the Conclave!",
			},
			randomize_indexes = {},
		},
	},
	broker_male_c = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 3,
			sound_events = {
				"loc_broker_male_c__com_wheel_vo_for_the_emperor_01",
				"loc_broker_male_c__com_wheel_vo_for_the_emperor_02",
				"loc_broker_male_c__com_wheel_vo_for_the_emperor_03",
			},
			sound_events_duration = {
				1.497083,
				1.556156,
				1.443854,
			},
			texts = {
				"For the Conclave!",
				"For Atoma!",
				"For freedom!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 1,
			sound_events = {
				"loc_broker_male_c__com_wheel_vo_for_the_emperor_01",
			},
			sound_events_duration = {
				1.497083,
			},
			texts = {
				"For the Conclave!",
			},
			randomize_indexes = {},
		},
	},
	cryptic_a = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 3,
			sound_events = {
				"loc_cryptic_a__com_wheel_vo_for_the_emperor_01",
				"loc_cryptic_a__com_wheel_vo_for_the_emperor_02",
				"loc_cryptic_a__com_wheel_vo_for_the_emperor_03",
			},
			sound_events_duration = {
				1.534323,
				1.332646,
				1.680104,
			},
			texts = {
				"For the Omnissiah!",
				"For Atoma!",
				"For the Imperium!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 1,
			sound_events = {
				"loc_cryptic_a__com_wheel_vo_for_the_emperor_01",
			},
			sound_events_duration = {
				1.534323,
			},
			texts = {
				"For the Omnissiah!",
			},
			randomize_indexes = {},
		},
	},
	cryptic_b = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 3,
			sound_events = {
				"loc_cryptic_b__com_wheel_vo_for_the_emperor_01",
				"loc_cryptic_b__com_wheel_vo_for_the_emperor_02",
				"loc_cryptic_b__com_wheel_vo_for_the_emperor_03",
			},
			sound_events_duration = {
				1.684708,
				1.380656,
				1.529656,
			},
			texts = {
				"For the Omnissiah!",
				"For Atoma!",
				"For the Imperium!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 1,
			sound_events = {
				"loc_cryptic_b__com_wheel_vo_for_the_emperor_01",
			},
			sound_events_duration = {
				1.684708,
			},
			texts = {
				"For the Omnissiah!",
			},
			randomize_indexes = {},
		},
	},
	cryptic_c = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 3,
			sound_events = {
				"loc_cryptic_c__com_wheel_vo_for_the_emperor_01",
				"loc_cryptic_c__com_wheel_vo_for_the_emperor_02",
				"loc_cryptic_c__com_wheel_vo_for_the_emperor_03",
			},
			sound_events_duration = {
				1.905385,
				1.302167,
				1.811104,
			},
			texts = {
				"For the Machine God!",
				"For Atoma!",
				"For the Imperium!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 1,
			sound_events = {
				"loc_cryptic_c__com_wheel_vo_for_the_emperor_01",
			},
			sound_events_duration = {
				1.905385,
			},
			texts = {
				"For the Machine God!",
			},
			randomize_indexes = {},
		},
	},
	cryptic_d = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 3,
			sound_events = {
				"loc_cryptic_d__com_wheel_vo_for_the_emperor_01",
				"loc_cryptic_d__com_wheel_vo_for_the_emperor_02",
				"loc_cryptic_d__com_wheel_vo_for_the_emperor_03",
			},
			sound_events_duration = {
				2.429823,
				1.681406,
				1.984083,
			},
			texts = {
				"For the Machine God!",
				"For Atoma!",
				"For the Imperium!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 1,
			sound_events = {
				"loc_cryptic_d__com_wheel_vo_for_the_emperor_01",
			},
			sound_events_duration = {
				2.429823,
			},
			texts = {
				"For the Machine God!",
			},
			randomize_indexes = {},
		},
	},
	ogryn_a = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 4,
			sound_events = {
				"loc_ogryn_a__com_wheel_vo_for_the_emperor_01",
				"loc_ogryn_a__com_wheel_vo_for_the_emperor_02",
				"loc_ogryn_a__com_wheel_vo_for_the_emperor_05",
				"loc_ogryn_a__com_wheel_vo_for_the_emperor_06",
			},
			sound_events_duration = {
				2.07974,
				1.867604,
				2.018583,
				2.231677,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
				"For Atoma!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_ogryn_a__com_wheel_vo_for_the_emperor_01",
				"loc_ogryn_a__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				2.07974,
				1.867604,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
			},
			randomize_indexes = {},
		},
	},
	ogryn_b = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 4,
			sound_events = {
				"loc_ogryn_b__com_wheel_vo_for_the_emperor_01",
				"loc_ogryn_b__com_wheel_vo_for_the_emperor_02",
				"loc_ogryn_b__com_wheel_vo_for_the_emperor_05",
				"loc_ogryn_b__com_wheel_vo_for_the_emperor_06",
			},
			sound_events_duration = {
				2.182958,
				1.94125,
				2.681531,
				2.654458,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
				"For Atoma!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_ogryn_b__com_wheel_vo_for_the_emperor_01",
				"loc_ogryn_b__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				2.182958,
				1.94125,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
			},
			randomize_indexes = {},
		},
	},
	ogryn_c = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 4,
			sound_events = {
				"loc_ogryn_c__com_wheel_vo_for_the_emperor_01",
				"loc_ogryn_c__com_wheel_vo_for_the_emperor_02",
				"loc_ogryn_c__com_wheel_vo_for_the_emperor_05",
				"loc_ogryn_c__com_wheel_vo_for_the_emperor_06",
			},
			sound_events_duration = {
				1.988177,
				2.519115,
				1.771365,
				1.972042,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
				"For Atoma!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_ogryn_c__com_wheel_vo_for_the_emperor_01",
				"loc_ogryn_c__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				1.988177,
				2.519115,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
			},
			randomize_indexes = {},
		},
	},
	ogryn_d = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 4,
			sound_events = {
				"loc_ogryn_d__com_wheel_vo_for_the_emperor_01",
				"loc_ogryn_d__com_wheel_vo_for_the_emperor_02",
				"loc_ogryn_d__com_wheel_vo_for_the_emperor_05",
				"loc_ogryn_d__com_wheel_vo_for_the_emperor_06",
			},
			sound_events_duration = {
				2.923615,
				2.099719,
				2.440406,
				2.496021,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
				"For Atoma!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_ogryn_d__com_wheel_vo_for_the_emperor_01",
				"loc_ogryn_d__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				2.923615,
				2.099719,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
			},
			randomize_indexes = {},
		},
	},
	psyker_female_a = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_psyker_female_a__com_wheel_vo_for_the_emperor_01",
				"loc_psyker_female_a__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				2.62225,
				2.184583,
			},
			texts = {
				"\"For the Emperor\" ... I'm sure ...",
				"\"For the Emperor\" ... I'm sure ...",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_psyker_female_a__com_wheel_vo_for_the_emperor_01",
				"loc_psyker_female_a__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				2.62225,
				2.184583,
			},
			texts = {
				"\"For the Emperor\" ... I'm sure ...",
				"\"For the Emperor\" ... I'm sure ...",
			},
			randomize_indexes = {},
		},
	},
	psyker_female_b = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 4,
			sound_events = {
				"loc_psyker_female_b__com_wheel_vo_for_the_emperor_01",
				"loc_psyker_female_b__com_wheel_vo_for_the_emperor_02",
				"loc_psyker_female_b__com_wheel_vo_for_the_emperor_05",
				"loc_psyker_female_b__com_wheel_vo_for_the_emperor_06",
			},
			sound_events_duration = {
				2.077625,
				2.123854,
				1.842021,
				1.892958,
			},
			texts = {
				"For my Beloved!",
				"For my Beloved!",
				"For Atoma!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_psyker_female_b__com_wheel_vo_for_the_emperor_01",
				"loc_psyker_female_b__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				2.077625,
				2.123854,
			},
			texts = {
				"For my Beloved!",
				"For my Beloved!",
			},
			randomize_indexes = {},
		},
	},
	psyker_female_c = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 5,
			sound_events = {
				"loc_psyker_female_c__com_wheel_vo_for_the_emperor_01",
				"loc_psyker_female_c__com_wheel_vo_for_the_emperor_02",
				"loc_psyker_female_c__com_wheel_vo_for_the_emperor_03",
				"loc_psyker_female_c__com_wheel_vo_for_the_emperor_05",
				"loc_psyker_female_c__com_wheel_vo_for_the_emperor_06",
			},
			sound_events_duration = {
				1.977094,
				2.133969,
				2.18101,
				2.14099,
				2.215042,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
				"For the Lex Atoma!",
				"For Atoma!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_psyker_female_c__com_wheel_vo_for_the_emperor_01",
				"loc_psyker_female_c__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				1.977094,
				2.133969,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
			},
			randomize_indexes = {},
		},
	},
	psyker_male_a = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_psyker_male_a__com_wheel_vo_for_the_emperor_01",
				"loc_psyker_male_a__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				2.802958,
				2.628854,
			},
			texts = {
				"\"For the Emperor\" ... I'm sure ...",
				"\"For the Emperor\" ... I'm sure ...",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_psyker_male_a__com_wheel_vo_for_the_emperor_01",
				"loc_psyker_male_a__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				2.802958,
				2.628854,
			},
			texts = {
				"\"For the Emperor\" ... I'm sure ...",
				"\"For the Emperor\" ... I'm sure ...",
			},
			randomize_indexes = {},
		},
	},
	psyker_male_b = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 4,
			sound_events = {
				"loc_psyker_male_b__com_wheel_vo_for_the_emperor_01",
				"loc_psyker_male_b__com_wheel_vo_for_the_emperor_02",
				"loc_psyker_male_b__com_wheel_vo_for_the_emperor_05",
				"loc_psyker_male_b__com_wheel_vo_for_the_emperor_06",
			},
			sound_events_duration = {
				1.084646,
				1.607438,
				1.263,
				1.154792,
			},
			texts = {
				"For my Beloved!",
				"For my Beloved!",
				"For Atoma!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_psyker_male_b__com_wheel_vo_for_the_emperor_01",
				"loc_psyker_male_b__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				1.084646,
				1.607438,
			},
			texts = {
				"For my Beloved!",
				"For my Beloved!",
			},
			randomize_indexes = {},
		},
	},
	psyker_male_c = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 5,
			sound_events = {
				"loc_psyker_male_c__com_wheel_vo_for_the_emperor_01",
				"loc_psyker_male_c__com_wheel_vo_for_the_emperor_02",
				"loc_psyker_male_c__com_wheel_vo_for_the_emperor_03",
				"loc_psyker_male_c__com_wheel_vo_for_the_emperor_05",
				"loc_psyker_male_c__com_wheel_vo_for_the_emperor_06",
			},
			sound_events_duration = {
				1.404156,
				1.460604,
				1.850938,
				1.674563,
				1.762427,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
				"For the Lex Atoma!",
				"For Atoma!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_psyker_male_c__com_wheel_vo_for_the_emperor_01",
				"loc_psyker_male_c__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				1.404156,
				1.460604,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
			},
			randomize_indexes = {},
		},
	},
	veteran_female_a = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 5,
			sound_events = {
				"loc_veteran_female_a__com_wheel_vo_for_the_emperor_01",
				"loc_veteran_female_a__com_wheel_vo_for_the_emperor_02",
				"loc_veteran_female_a__com_wheel_vo_for_the_emperor_03",
				"loc_veteran_female_a__com_wheel_vo_for_the_emperor_05",
				"loc_veteran_female_a__com_wheel_vo_for_the_emperor_06",
			},
			sound_events_duration = {
				1.604771,
				2.325708,
				1.283438,
				1.220167,
				1.192563,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
				"For the Throne!",
				"For Atoma!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_veteran_female_a__com_wheel_vo_for_the_emperor_01",
				"loc_veteran_female_a__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				1.604771,
				2.325708,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
			},
			randomize_indexes = {},
		},
	},
	veteran_female_b = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 4,
			sound_events = {
				"loc_veteran_female_b__com_wheel_vo_for_the_emperor_01",
				"loc_veteran_female_b__com_wheel_vo_for_the_emperor_02",
				"loc_veteran_female_b__com_wheel_vo_for_the_emperor_05",
				"loc_veteran_female_b__com_wheel_vo_for_the_emperor_06",
			},
			sound_events_duration = {
				1.237854,
				1.329917,
				1.005396,
				1.264542,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
				"For Atoma!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_veteran_female_b__com_wheel_vo_for_the_emperor_01",
				"loc_veteran_female_b__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				1.237854,
				1.329917,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
			},
			randomize_indexes = {},
		},
	},
	veteran_female_c = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 4,
			sound_events = {
				"loc_veteran_female_c__com_wheel_vo_for_the_emperor_01",
				"loc_veteran_female_c__com_wheel_vo_for_the_emperor_02",
				"loc_veteran_female_c__com_wheel_vo_for_the_emperor_05",
				"loc_veteran_female_c__com_wheel_vo_for_the_emperor_06",
			},
			sound_events_duration = {
				1.550385,
				1.495385,
				1.478875,
				1.745708,
			},
			texts = {
				"For Cadia!",
				"For Cadia!",
				"For Atoma!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_veteran_female_c__com_wheel_vo_for_the_emperor_01",
				"loc_veteran_female_c__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				1.550385,
				1.495385,
			},
			texts = {
				"For Cadia!",
				"For Cadia!",
			},
			randomize_indexes = {},
		},
	},
	veteran_male_a = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 5,
			sound_events = {
				"loc_veteran_male_a__com_wheel_vo_for_the_emperor_01",
				"loc_veteran_male_a__com_wheel_vo_for_the_emperor_02",
				"loc_veteran_male_a__com_wheel_vo_for_the_emperor_03",
				"loc_veteran_male_a__com_wheel_vo_for_the_emperor_05",
				"loc_veteran_male_a__com_wheel_vo_for_the_emperor_06",
			},
			sound_events_duration = {
				1.309104,
				1.580458,
				1.540333,
				0.916813,
				1.5945,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
				"For the Throne!",
				"For Atoma!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_veteran_male_a__com_wheel_vo_for_the_emperor_01",
				"loc_veteran_male_a__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				1.309104,
				1.580458,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
			},
			randomize_indexes = {},
		},
	},
	veteran_male_b = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 4,
			sound_events = {
				"loc_veteran_male_b__com_wheel_vo_for_the_emperor_01",
				"loc_veteran_male_b__com_wheel_vo_for_the_emperor_02",
				"loc_veteran_male_b__com_wheel_vo_for_the_emperor_05",
				"loc_veteran_male_b__com_wheel_vo_for_the_emperor_06",
			},
			sound_events_duration = {
				1.606,
				1.058625,
				0.966938,
				1.354583,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
				"For Atoma!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_veteran_male_b__com_wheel_vo_for_the_emperor_01",
				"loc_veteran_male_b__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				1.606,
				1.058625,
			},
			texts = {
				"For the Emperor!",
				"For the Emperor!",
			},
			randomize_indexes = {},
		},
	},
	veteran_male_c = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 4,
			sound_events = {
				"loc_veteran_male_c__com_wheel_vo_for_the_emperor_01",
				"loc_veteran_male_c__com_wheel_vo_for_the_emperor_02",
				"loc_veteran_male_c__com_wheel_vo_for_the_emperor_05",
				"loc_veteran_male_c__com_wheel_vo_for_the_emperor_06",
			},
			sound_events_duration = {
				1.268938,
				1.125885,
				1.314677,
				0.857635,
			},
			texts = {
				"For Cadia!",
				"For Cadia!",
				"For Atoma!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_veteran_male_c__com_wheel_vo_for_the_emperor_01",
				"loc_veteran_male_c__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				1.268938,
				1.125885,
			},
			texts = {
				"For Cadia!",
				"For Cadia!",
			},
			randomize_indexes = {},
		},
	},
	zealot_female_a = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 4,
			sound_events = {
				"loc_zealot_female_a__com_wheel_vo_for_the_emperor_01",
				"loc_zealot_female_a__com_wheel_vo_for_the_emperor_02",
				"loc_zealot_female_a__com_wheel_vo_for_the_emperor_05",
				"loc_zealot_female_a__com_wheel_vo_for_the_emperor_06",
			},
			sound_events_duration = {
				2.055146,
				1.819625,
				0.787542,
				1.180396,
			},
			texts = {
				"For the Master of Mankind!",
				"For the Master of Mankind!",
				"For Atoma!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_zealot_female_a__com_wheel_vo_for_the_emperor_01",
				"loc_zealot_female_a__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				2.055146,
				1.819625,
			},
			texts = {
				"For the Master of Mankind!",
				"For the Master of Mankind!",
			},
			randomize_indexes = {},
		},
	},
	zealot_female_b = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 4,
			sound_events = {
				"loc_zealot_female_b__com_wheel_vo_for_the_emperor_01",
				"loc_zealot_female_b__com_wheel_vo_for_the_emperor_02",
				"loc_zealot_female_b__com_wheel_vo_for_the_emperor_05",
				"loc_zealot_female_b__com_wheel_vo_for_the_emperor_06",
			},
			sound_events_duration = {
				1.571063,
				1.640625,
				1.365313,
				1.469271,
			},
			texts = {
				"For the God-Emperor!",
				"For the God-Emperor!",
				"For Atoma!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_zealot_female_b__com_wheel_vo_for_the_emperor_01",
				"loc_zealot_female_b__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				1.571063,
				1.640625,
			},
			texts = {
				"For the God-Emperor!",
				"For the God-Emperor!",
			},
			randomize_indexes = {},
		},
	},
	zealot_female_c = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 4,
			sound_events = {
				"loc_zealot_female_c__com_wheel_vo_for_the_emperor_01",
				"loc_zealot_female_c__com_wheel_vo_for_the_emperor_02",
				"loc_zealot_female_c__com_wheel_vo_for_the_emperor_05",
				"loc_zealot_female_c__com_wheel_vo_for_the_emperor_06",
			},
			sound_events_duration = {
				2.647438,
				1.762948,
				2.118677,
				1.407073,
			},
			texts = {
				"For the Beneficent Emperor!",
				"For the Beneficent Emperor!",
				"For Atoma!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_zealot_female_c__com_wheel_vo_for_the_emperor_01",
				"loc_zealot_female_c__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				2.647438,
				1.762948,
			},
			texts = {
				"For the Beneficent Emperor!",
				"For the Beneficent Emperor!",
			},
			randomize_indexes = {},
		},
	},
	zealot_male_a = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 3,
			sound_events = {
				"loc_zealot_male_a__com_wheel_vo_for_the_emperor_01",
				"loc_zealot_male_a__com_wheel_vo_for_the_emperor_02",
				"loc_zealot_male_a__com_wheel_vo_for_the_emperor_06",
			},
			sound_events_duration = {
				2.547771,
				2.817104,
				1.879542,
			},
			texts = {
				"For the Master of Mankind!",
				"For the Master of Mankind!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_zealot_male_a__com_wheel_vo_for_the_emperor_01",
				"loc_zealot_male_a__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				2.547771,
				2.817104,
			},
			texts = {
				"For the Master of Mankind!",
				"For the Master of Mankind!",
			},
			randomize_indexes = {},
		},
	},
	zealot_male_b = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 4,
			sound_events = {
				"loc_zealot_male_b__com_wheel_vo_for_the_emperor_01",
				"loc_zealot_male_b__com_wheel_vo_for_the_emperor_02",
				"loc_zealot_male_b__com_wheel_vo_for_the_emperor_05",
				"loc_zealot_male_b__com_wheel_vo_for_the_emperor_06",
			},
			sound_events_duration = {
				2.481167,
				2.377417,
				1.085167,
				1.384104,
			},
			texts = {
				"For the God-Emperor!",
				"For the God-Emperor!",
				"For Atoma!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_zealot_male_b__com_wheel_vo_for_the_emperor_01",
				"loc_zealot_male_b__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				2.481167,
				2.377417,
			},
			texts = {
				"For the God-Emperor!",
				"For the God-Emperor!",
			},
			randomize_indexes = {},
		},
	},
	zealot_male_c = {
		all = {
			randomize_indexes_n = 0,
			sound_events_n = 4,
			sound_events = {
				"loc_zealot_male_c__com_wheel_vo_for_the_emperor_01",
				"loc_zealot_male_c__com_wheel_vo_for_the_emperor_02",
				"loc_zealot_male_c__com_wheel_vo_for_the_emperor_05",
				"loc_zealot_male_c__com_wheel_vo_for_the_emperor_06",
			},
			sound_events_duration = {
				1.881323,
				2.27774,
				1.459427,
				1.675719,
			},
			texts = {
				"For the Beneficent Emperor!",
				"For the Beneficent Emperor!",
				"For Atoma!",
				"For Atoma!",
			},
			randomize_indexes = {},
		},
		prefer_fte = {
			randomize_indexes_n = 0,
			sound_events_n = 2,
			sound_events = {
				"loc_zealot_male_c__com_wheel_vo_for_the_emperor_01",
				"loc_zealot_male_c__com_wheel_vo_for_the_emperor_02",
			},
			sound_events_duration = {
				1.881323,
				2.27774,
			},
			texts = {
				"For the Beneficent Emperor!",
				"For the Beneficent Emperor!",
			},
			randomize_indexes = {},
		},
	},
}
